exports.BattleMovedex = {
              "flameshot": {
		num: 2000,
		accuracy: 100,
		basePower: 40,
		category: "Physical",
		desc: "Deals damage to one adjacent target. Priority +1.",
		shortDesc: "Usually goes first.",
		id: "Flame Shot",
		isViable: true,
		name: "Flame Shot",
		pp: 30,
		priority: 1,
		secondary: false,
		target: "normal",
		type: "Fire"
	      },
	      "sapblast": {
		num: 2001,
		accuracy: 100,
		basePower: 40,
		category: "Physical",
		desc: "Deals damage to one adjacent target. Priority +1.",
		shortDesc: "Usually goes first.",
		id: "Sap Blast",
		isViable: true,
		name: "Sap Blast",
		pp: 30,
		priority: 1,
		secondary: false,
		target: "normal",
		type: "Grass"
	      },
	      "kineticforce": {
		num: 2002,
		accuracy: 100,
		basePower: 40,
		category: "Special",
		desc: "Deals damage to one adjacent target. Priority +1.",
		shortDesc: "Usually goes first.",
		id: "Kinetic Force",
		isViable: true,
		name: "Kinetic Force",
		pp: 30,
		priority: 1,
		secondary: false,
		target: "normal",
		type: "Psychic"
	      },
	      "stonespine": {
		num: 2003,
		accuracy: 90,
		basePower: 55,
		category: "Physical",
		desc: "Deals damage to one adjacent target. Priority +1.",
		shortDesc: "Usually goes first.",
		id: "Stone Spine",
		isViable: true,
		name: "Stone Spine",
		pp: 30,
		priority: 1,
		isContact: true,
		secondary: false,
		target: "normal",
		type: "Rock"
	      },
	      "dracocrash": {
		num: 2004,
		accuracy: 90,
		basePower: 50,
		category: "Physical",
		desc: "Deals damage to one adjacent target. Priority +1.",
		shortDesc: "Usually goes first.",
		id: "Draco Crash",
		isViable: true,
		name: "Draco Crash",
		pp: 30,
		priority: 2,
		isContact: true,
		secondary: false,
		target: "normal",
		type: "Dragon"
	      },
	      "venomstrike": {
		num: 2005,
		accuracy: 100,
		basePower: 30,
		category: "Physical",
		desc: "Deals damage to one adjacent target.",
		shortDesc: "Usually goes first, 30% chance to badly poison the target.",
		id: "Venom Strike",
		name: "Venom Strike",
		pp: 30,
		priority: 1,
		isContact: true,
		secondary: {
			chance: 30,
			status: 'tox'
		},
		target: "normal",
		type: "Poison"
	      },
	      "fairywind": {
		num: 584,
		accuracy: 100,
		basePower: 40,
		category: "Special",
		desc: "Deals damage to one adjacent target.",
		shortDesc: "Usually goes first.",
		id: "fairywind",
		name: "Fairy Wind",
		pp: 30,
		priority: 1,
		secondary: false,
		target: "normal",
		type: "Fairy"
	      },
};	      
